<?
$PERM["mebindex.php"]["5"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["10"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["9"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["10"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["/"]["10"]="X";
$PERM["/"]["*"]="R";
$PERM["bitrix"]["10"]="D";
$PERM["bitrix"]["*"]="D";
$PERM["obyavleniya"]["10"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>